authServiceDb {
  poolName = "quill"
  maximumPoolSize = 3
  connectionTimeout = 20000
  transactionIsolation = TRANSACTION_SERIALIZABLE
  dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
  dataSource {
    url = ${BASE_JDBC_URL}"/"${AUTH_SERVICE_DB_NAME}
    user = ${DB_USER}
    password = ${DB_PASSWORD}
  }
  migrations{
    enabled = true          
    locations = ["classpath:db/migration/auth"]
  }
}
passwordHashing {
  iterations = ${PH_ITERATIONS}
  memoryKiB = ${PH_MEMORY_IN_KB}
  parallelism = ${PH_PARALLELISM}
  saltLength = ${PH_SALT}
  hashLength = ${PH_HASH}
}
frontend{
  baseUrl= ${FRONTEND_BASE_URL}
  confirmRegistrationPath= ${FRONTEND_CONFIRM_REGISTRATION_PATH}
}
emailService{
  Host= ${EMAIL_HOST}
  Port= ${EMAIL_POST}
  User= ${EMAIL_USER}
  Password= ${EMAIL_PASSWORD}
}
