authServiceDb {
  poolName = "quill"
  maximumPoolSize = 3
  connectionTimeout = 20000
  transactionIsolation = TRANSACTION_SERIALIZABLE
  dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
  dataSource {
    url = "jdbc:postgresql://"${POSTGRES_HOST}":"${POSTGRES_HOST_PORT}"/"${AUTH_SERVICE_DB_NAME}
    user = ${DB_USER}
    password = ${DB_PASSWORD}
  }
  
}
serviceDbMigrations {
    enabled = true
    locations = ["classpath:db/migration/"${AUTH_SERVICE_DB_NAME}]
  }
passwordHashing {
  iterations = ${PASSWORD_HASHING_ITERATIONS}
  memoryKiB = ${PASSWORD_HASHING_MEMORY_IN_KB}
  parallelism = ${PASSWORD_HASHING_PARALLELISM}
  saltLength = ${PASSWORD_HASHING_SALT}
  hashLength = ${PASSWORD_HASHING_HASH}
}
frontend {
  baseUrl = ${FRONTEND_BASE_URL}
  confirmRegistrationPath = ${FRONTEND_CONFIRM_REGISTRATION_PATH}
}
emailService {
  sender = ${EMAIL_SENDER}
  host = ${EMAIL_HOST}
  port = ${EMAIL_PORT}
  user = ${EMAIL_USER}
  pass = ${EMAIL_PASSWORD}
}
webAuth{
    accessTokenIssuing {
      issuer = ${JWT_ISSUER}
      audience = ${JWT_AUDIENCE}
      keyId = ${JWT_KEY_ID}
      publicKeyPem = ${JWT_PUBLIC_KEY_PEM}
      privateKeyPem = ${JWT_PRIVATE_KEY_PEM}
      ttlSeconds = ${JWT_ACCESS_TTL_SECONDS}
    }
    
    refreshToken {
      ttlSeconds = ${REFRESH_TOKEN_TTL_SECONDS}
      hmacSecret = ${REFRESH_TOKEN_HMAC_SECRET}
    }

  authCookieNames {
    accessTokenCookie = "access_token"
    unauthenticatedCtxIdentifierCookie = "unauth_ctx_id"
  }
}


